import {Router} from 'express';
import {z} from 'zod';
import type {Server} from 'socket.io';
import {prisma} from '../lib/db.js';
import {audit} from '../lib/audit.js';
import {currentAdmin,currentOrganization,requireCsrf} from '../lib/auth.js';
import {decryptSecret,encryptSecret,generateAccessKey,generateTeamAccessKey,hashSecret,lookupHash,normalizeKey,randomToken,tokenHash} from '../lib/security.js';
import {defaultStepsForBestOf,validateVetoSteps} from '../domain/veto.js';
import {defaultVctFlows,eventFlowInput,eventFlowSteps,mapPoolInput} from '../domain/event-flow.js';
import {vetoSnapshot,overlayDto} from '../services/snapshot.js';
import {submitSide} from '../services/veto-service.js';
import {syncValorantMaps} from '../services/map-sync.js';
import {validateRemoteImageUrl} from '../lib/remote-image.js';
import {env} from '../config/env.js';
import {deleteEvent,deleteOrganization,deleteVetoSession,restoreEvent,restoreOrganization,restoreVetoSession} from '../services/recycle-bin.js';
import {readServerLogs} from '../lib/logger.js';

const eventInput=z.object({organizationId:z.string().optional(),name:z.string().min(1).max(120),description:z.string().max(2000).optional(),logoPath:z.string().regex(/^\/uploads\/events\/[A-Za-z0-9._-]+$/).optional(),logoUrl:z.string().url().refine(v=>v.startsWith('https://'),'Logo URL 必須使用 HTTPS').optional().or(z.literal('')),startsAt:z.string().datetime().optional().or(z.literal('')),endsAt:z.string().datetime().optional().or(z.literal('')),themeColor:z.string().regex(/^#[0-9a-f]{6}$/i),defaultKeyTtlMinutes:z.number().int().min(15).max(525600),publicSharingEnabled:z.boolean(),mapIds:mapPoolInput});
const timerSeconds=z.number().int().min(-1).max(3600);
const bpInput=z.object({eventId:z.string(),name:z.string().min(1).max(120),bestOf:z.union([z.literal(1),z.literal(3),z.literal(5)]).default(3),teamAName:z.string().min(1).max(100),teamALogo:z.string().max(500).optional(),teamBName:z.string().min(1).max(100),teamBLogo:z.string().max(500).optional(),keyExpiresAt:z.string().datetime(),mapSelectionSeconds:timerSeconds.default(-1),sideSelectionSeconds:timerSeconds.default(-1),overlayTheme:z.enum(['vct-en','vct-en-i','vct-tc','vct-tc-i']).default('vct-tc'),publicSharingEnabled:z.boolean().optional(),flowId:z.string().optional(),steps:z.array(z.any()).optional()});
const organizationInput=z.object({name:z.string().min(1).max(120),iconPath:z.string().regex(/^(\/branding\/PulseVeto_Favicon\.png|\/uploads\/organizations\/[A-Za-z0-9._-]+)$/).default('/branding/PulseVeto_Favicon.png'),description:z.string().max(1000).optional(),expiresAt:z.string().datetime(),status:z.enum(['ACTIVE','SUSPENDED','ARCHIVED']).optional(),discordUserIds:z.array(z.string().regex(/^\d{17,20}$/)).max(25).refine(values=>new Set(values).size===values.length,'Discord User ID 不得重複').optional()});
const bpUpdateInput=z.object({name:z.string().min(1).max(120).optional(),bestOf:z.union([z.literal(1),z.literal(3),z.literal(5)]).optional(),teamAName:z.string().min(1).max(100).optional(),teamALogo:z.string().max(500).optional(),teamBName:z.string().min(1).max(100).optional(),teamBLogo:z.string().max(500).optional(),keyExpiresAt:z.string().datetime().optional(),mapSelectionSeconds:timerSeconds.optional(),sideSelectionSeconds:timerSeconds.optional(),publicSharingEnabled:z.boolean().optional()});
const discordMemberInput=z.object({discordUserId:z.string().regex(/^\d{17,20}$/),organizationId:z.string().optional()});
const discordAccountInput=z.object({username:z.string().min(1).max(100),organizationIds:z.array(z.string()).max(25).refine(values=>new Set(values).size===values.length)});

async function identity(req:Parameters<typeof currentAdmin>[0]){const admin=await currentAdmin(req);if(admin)return{role:'PULSE' as const,id:admin.adminUserId,admin};const org=await currentOrganization(req);if(org)return{role:'ORGANIZATION' as const,id:org.organizationId,org};return null}
async function csrfRecord(req:Parameters<typeof currentAdmin>[0]){return await currentAdmin(req)||await currentOrganization(req)}
async function ownsEvent(who:Awaited<ReturnType<typeof identity>>,eventId:string){if(!who)return null;const event=await prisma.event.findUnique({where:{id:eventId}});return event&&(who.role==='PULSE'||event.organizationId===who.id)?event:null}
function deny(res:any){return res.status(403).json({error:'沒有權限執行此操作'})}

export function manageRouter(io:Server){const r=Router();r.use(async(req,res,next)=>{if(!await identity(req))return res.status(401).json({error:'Session expired'});next()});r.use(async(req,res,next)=>{try{for(const value of [req.body?.logoUrl,req.body?.teamALogo,req.body?.teamBLogo])if(typeof value==='string'&&value)await validateRemoteImageUrl(value);next()}catch(error){res.status(400).json({error:(error as Error).message})}});
  r.get('/server-logs',async(req,res)=>{const who=await identity(req);if(!who||who.role!=='PULSE')return res.status(403).json({error:'只有 Pulse Studio 全域管理員可以查看 Server Log'});const limit=z.coerce.number().int().min(20).max(1000).default(300).parse(req.query.limit);res.set('Cache-Control','no-store').json({lines:await readServerLogs(limit)})});
  r.get('/release-notes',async(_req,res)=>{
    res.json(await prisma.releaseNote.findMany({orderBy:{createdAt:'desc'},take:100}));
  });
  r.post('/release-notes',requireCsrf(csrfRecord),async(req,res)=>{
    const who=(await identity(req))!;if(who.role!=='PULSE')return deny(res);
    const body=z.object({version:z.string().trim().min(1).max(80),body:z.string().trim().min(1).max(20000)}).parse(req.body);
    if(await prisma.releaseNote.findUnique({where:{version:body.version}}))return res.status(409).json({error:'此版本已存在，請編輯原更新日誌'});
    const note=await prisma.releaseNote.create({data:body});
    await audit({action:'RELEASE_NOTE_CREATED',actorType:who.role,actorId:who.id,entityId:note.id,ip:req.ip});res.status(201).json(note);
  });
  r.patch('/release-notes/:id',requireCsrf(csrfRecord),async(req,res)=>{
    const who=(await identity(req))!;if(who.role!=='PULSE')return deny(res);
    const id=String(req.params.id),body=z.object({body:z.string().trim().min(1).max(20000)}).parse(req.body);
    if(!await prisma.releaseNote.findUnique({where:{id}}))return res.sendStatus(404);
    const note=await prisma.releaseNote.update({where:{id},data:body});
    await audit({action:'RELEASE_NOTE_UPDATED',actorType:who.role,actorId:who.id,entityId:id,ip:req.ip});res.json(note);
  });
  r.delete('/release-notes/:id',requireCsrf(csrfRecord),async(req,res)=>{
    const who=(await identity(req))!;if(who.role!=='PULSE')return deny(res);
    const id=String(req.params.id),note=await prisma.releaseNote.findUnique({where:{id}});if(!note)return res.sendStatus(404);
    await prisma.releaseNote.delete({where:{id}});
    await audit({action:'RELEASE_NOTE_DELETED',actorType:who.role,actorId:who.id,entityId:id,ip:req.ip,details:{version:note.version}});res.json({ok:true});
  });
  r.get('/events/:id/flows',async(req,res)=>{
    const who=(await identity(req))!,event=await ownsEvent(who,String(req.params.id));if(!event||event.deletedAt)return deny(res);
    const flows=await prisma.eventVetoFlow.findMany({where:{eventId:event.id},orderBy:{createdAt:'asc'}});
    res.json(flows.map(({stepsJson,...flow})=>({...flow,steps:JSON.parse(stepsJson)})));
  });
  r.post('/events/:id/flows',requireCsrf(csrfRecord),async(req,res)=>{
    const who=(await identity(req))!,event=await ownsEvent(who,String(req.params.id));if(!event||event.deletedAt)return deny(res);
    const body=eventFlowInput.parse(req.body);
    const flow=await prisma.$transaction(async tx=>{
      const count=await tx.eventMap.count({where:{eventId:event.id}}),steps=eventFlowSteps(body,count);
      if(await tx.eventVetoFlow.findUnique({where:{eventId_name:{eventId:event.id,name:body.name}}}))throw Object.assign(new Error('流程名稱已存在'),{status:409});
      return tx.eventVetoFlow.create({data:{eventId:event.id,name:body.name,stepsJson:JSON.stringify(steps)}});
    });
    await audit({action:'EVENT_FLOW_CREATED',actorType:who.role,actorId:who.id,organizationId:event.organizationId,eventId:event.id,entityId:flow.id,ip:req.ip});res.status(201).json(flow);
  });
  r.put('/events/:id/flows/:flowId',requireCsrf(csrfRecord),async(req,res)=>{
    const who=(await identity(req))!,event=await ownsEvent(who,String(req.params.id));if(!event||event.deletedAt)return deny(res);
    const id=String(req.params.flowId),body=eventFlowInput.parse(req.body);
    const flow=await prisma.$transaction(async tx=>{
      if(!await tx.eventVetoFlow.findFirst({where:{id,eventId:event.id}}))throw Object.assign(new Error('找不到流程'),{status:404});
      const steps=eventFlowSteps(body,await tx.eventMap.count({where:{eventId:event.id}}));
      if(await tx.eventVetoFlow.findFirst({where:{eventId:event.id,name:body.name,id:{not:id}}}))throw Object.assign(new Error('流程名稱已存在'),{status:409});
      return tx.eventVetoFlow.update({where:{id},data:{name:body.name,stepsJson:JSON.stringify(steps)}});
    });
    await audit({action:'EVENT_FLOW_UPDATED',actorType:who.role,actorId:who.id,organizationId:event.organizationId,eventId:event.id,entityId:id,ip:req.ip});res.json(flow);
  });
  r.delete('/events/:id/flows/:flowId',requireCsrf(csrfRecord),async(req,res)=>{
    const who=(await identity(req))!,event=await ownsEvent(who,String(req.params.id));if(!event||event.deletedAt)return deny(res);
    const id=String(req.params.flowId),removed=await prisma.eventVetoFlow.deleteMany({where:{id,eventId:event.id}});
    if(!removed.count)return res.sendStatus(404);
    await audit({action:'EVENT_FLOW_DELETED',actorType:who.role,actorId:who.id,organizationId:event.organizationId,eventId:event.id,entityId:id,ip:req.ip});res.json({ok:true});
  });
  r.put('/discord-members',requireCsrf(csrfRecord),async(req,res)=>{const who=(await identity(req))!,body=discordMemberInput.parse(req.body),targetId=who.role==='PULSE'?body.organizationId:who.id;if(!targetId)return res.status(400).json({error:'請選擇賽事單位'});const [account,target]=await Promise.all([prisma.discordAccount.findUnique({where:{discordUserId:body.discordUserId}}),prisma.organization.findUnique({where:{id:targetId}})]);if(!target||target.status!=='ACTIVE')return res.status(400).json({error:'賽事單位不存在或目前未啟用'});await prisma.organizationDiscordMember.upsert({where:{organizationId_discordUserId:{organizationId:targetId,discordUserId:body.discordUserId}},create:{organizationId:targetId,discordUserId:body.discordUserId,username:account?.username,avatarUrl:account?.avatarUrl},update:{username:account?.username,avatarUrl:account?.avatarUrl}});await audit({action:'DISCORD_MEMBER_ASSIGNED',actorType:who.role,actorId:who.id,organizationId:targetId,entityType:'DISCORD_ACCOUNT',entityId:body.discordUserId,ip:req.ip,details:{pendingFirstLogin:!account}});res.json({ok:true,pendingFirstLogin:!account})});
  r.delete('/discord-members/:discordUserId',requireCsrf(csrfRecord),async(req,res)=>{const who=(await identity(req))!,discordUserId=z.string().regex(/^\d{17,20}$/).parse(String(req.params.discordUserId)),organizationId=who.role==='PULSE'?z.string().parse(req.query.organizationId):who.id,member=await prisma.organizationDiscordMember.findUnique({where:{organizationId_discordUserId:{organizationId,discordUserId}}});if(!member)return res.status(404).json({error:'此帳號目前沒有該賽事單位權限'});await prisma.organizationDiscordMember.delete({where:{id:member.id}});await audit({action:'DISCORD_MEMBER_REMOVED',actorType:who.role,actorId:who.id,organizationId,entityType:'DISCORD_ACCOUNT',entityId:discordUserId,ip:req.ip});res.json({ok:true})});
  r.patch('/discord-accounts/:discordUserId',requireCsrf(csrfRecord),async(req,res)=>{const who=(await identity(req))!;if(who.role!=='PULSE')return deny(res);const discordUserId=z.string().regex(/^\d{17,20}$/).parse(String(req.params.discordUserId)),body=discordAccountInput.parse(req.body),account=await prisma.discordAccount.findUnique({where:{discordUserId}}),membershipCount=await prisma.organizationDiscordMember.count({where:{discordUserId}});if(!account&&!membershipCount)return res.status(404).json({error:'找不到此 Discord 使用者'});const activeCount=await prisma.organization.count({where:{id:{in:body.organizationIds},deletedAt:null,status:'ACTIVE',OR:[{expiresAt:null},{expiresAt:{gt:new Date()}}]}});if(activeCount!==body.organizationIds.length)return res.status(400).json({error:'包含不存在、已停用或已到期的賽事單位'});await prisma.$transaction(async tx=>{if(account)await tx.discordAccount.update({where:{discordUserId},data:{username:body.username}});await tx.organizationDiscordMember.deleteMany({where:{discordUserId,organizationId:{notIn:body.organizationIds}}});for(const organizationId of body.organizationIds)await tx.organizationDiscordMember.upsert({where:{organizationId_discordUserId:{organizationId,discordUserId}},create:{organizationId,discordUserId,username:account?body.username:null,avatarUrl:account?.avatarUrl},update:{username:account?body.username:null,avatarUrl:account?.avatarUrl}})});await audit({action:'DISCORD_ACCOUNT_ASSIGNMENT_UPDATED',actorType:'PULSE_ADMIN',actorId:who.id,entityType:'DISCORD_ACCOUNT',entityId:discordUserId,ip:req.ip,details:{organizationIds:body.organizationIds}});res.json({ok:true})});
  r.delete('/discord-accounts/:discordUserId',requireCsrf(csrfRecord),async(req,res)=>{const who=(await identity(req))!,discordUserId=z.string().regex(/^\d{17,20}$/).parse(String(req.params.discordUserId));if(who.role==='ORGANIZATION'){const removed=await prisma.organizationDiscordMember.deleteMany({where:{organizationId:who.id,discordUserId}});if(!removed.count)return res.status(404).json({error:'此帳號目前沒有該賽事單位權限'});await audit({action:'DISCORD_MEMBER_REMOVED',actorType:who.role,actorId:who.id,organizationId:who.id,entityType:'DISCORD_ACCOUNT',entityId:discordUserId,ip:req.ip});return res.json({ok:true})}if(discordUserId===env.PULSE_DISCORD_USER_ID)return res.status(400).json({error:'Pulse Studio 最高管理員帳號不可刪除'});const [account,membershipCount]=await Promise.all([prisma.discordAccount.findUnique({where:{discordUserId}}),prisma.organizationDiscordMember.count({where:{discordUserId}})]);if(!account&&!membershipCount)return res.status(404).json({error:'找不到此 Discord 使用者'});await prisma.$transaction(async tx=>{await tx.organizationDiscordMember.deleteMany({where:{discordUserId}});if(account)await tx.discordAccount.delete({where:{discordUserId}})});await audit({action:'DISCORD_ACCOUNT_DELETED',actorType:'PULSE_ADMIN',actorId:who.id,entityType:'DISCORD_ACCOUNT',entityId:discordUserId,ip:req.ip});res.json({ok:true})});
  r.post('/organizations-discord',requireCsrf(csrfRecord),async(req,res)=>{const who=(await identity(req))!;if(who.role!=='PULSE')return deny(res);const body=organizationInput.parse(req.body),discordUserIds=body.discordUserIds||[];const org=await prisma.organization.create({data:{name:body.name,iconPath:body.iconPath,description:body.description,expiresAt:new Date(body.expiresAt),discordMembers:{create:discordUserIds.map(discordUserId=>({discordUserId}))}}});await audit({action:'ORGANIZATION_CREATED',actorType:'PULSE_ADMIN',actorId:who.id,organizationId:org.id,entityType:'ORGANIZATION',entityId:org.id,ip:req.ip,details:{discordUserIds}});res.status(201).json({organization:org})});
  r.patch('/organizations/:id/settings',requireCsrf(csrfRecord),async(req,res)=>{const who=(await identity(req))!;if(who.role!=='PULSE')return deny(res);const body=organizationInput.partial().parse(req.body),id=String(req.params.id);const org=await prisma.$transaction(async tx=>{const updated=await tx.organization.update({where:{id},data:{name:body.name,iconPath:body.iconPath,description:body.description,status:body.status,expiresAt:body.expiresAt?new Date(body.expiresAt):undefined}});if(body.discordUserIds){await tx.organizationDiscordMember.deleteMany({where:{organizationId:id}});if(body.discordUserIds.length)await tx.organizationDiscordMember.createMany({data:body.discordUserIds.map(discordUserId=>({organizationId:id,discordUserId}))})}return updated});await audit({action:'ORGANIZATION_UPDATED',actorType:'PULSE_ADMIN',actorId:who.id,organizationId:org.id,entityType:'ORGANIZATION',entityId:org.id,ip:req.ip,details:body});res.json(org)});
  r.patch('/veto-sessions/:id/settings',requireCsrf(csrfRecord),async(req,res)=>{const who=(await identity(req))!,id=String(req.params.id),body=bpUpdateInput.parse(req.body),existing=await prisma.vetoSession.findUnique({where:{id},include:{event:true,_count:{select:{actions:true}}}});if(!existing||!(await ownsEvent(who,existing.eventId)))return deny(res);if(body.bestOf!==undefined&&body.bestOf!==existing.bestOf&&existing.flowName)return res.status(409).json({error:'自訂流程的賽制由選圖數量決定，請建立新的 BP'});if(body.bestOf!==undefined&&body.bestOf!==existing.bestOf&&existing._count.actions>0)return res.status(409).json({error:'BP 已開始操作，不能再修改賽制'});const updated=await prisma.$transaction(async tx=>{if(body.bestOf!==undefined&&body.bestOf!==existing.bestOf){await tx.vetoStep.deleteMany({where:{vetoSessionId:id}});await tx.vetoStep.createMany({data:defaultStepsForBestOf(body.bestOf).map(step=>({vetoSessionId:id,...step,resultOrder:step.resultOrder??null,customLabel:step.customLabel??null,sideSelector:step.sideSelector??null}))})}if(body.keyExpiresAt)await tx.teamAccessKey.updateMany({where:{vetoSessionId:id,revokedAt:null},data:{expiresAt:new Date(body.keyExpiresAt)}});return tx.vetoSession.update({where:{id},data:{name:body.name,bestOf:body.bestOf,teamAName:body.teamAName,teamALogo:body.teamALogo,teamBName:body.teamBName,teamBLogo:body.teamBLogo,mapSelectionSeconds:body.mapSelectionSeconds,sideSelectionSeconds:body.sideSelectionSeconds,publicSharingEnabled:true,version:{increment:1}}})});await audit({action:'VETO_UPDATED',actorType:who.role,actorId:who.id,organizationId:existing.event.organizationId,eventId:existing.eventId,vetoSessionId:id,ip:req.ip,details:{...body,keyExpiresAt:body.keyExpiresAt?new Date(body.keyExpiresAt).toISOString():undefined}});const snap=await vetoSnapshot(id);io.to(`veto:${id}`).emit('veto:changed',{version:snap.version});io.to(`veto:${id}`).emit('state_changed',overlayDto(snap));res.json(updated)});
  r.get('/context',async(req,res)=>{const who=(await identity(req))!;const organizations=who.role==='PULSE'?await prisma.organization.findMany({orderBy:{createdAt:'desc'},select:{id:true,name:true,description:true,status:true,expiresAt:true,createdAt:true,keys:{where:{revokedAt:null},select:{lastFour:true,expiresAt:true}},discordMembers:{select:{discordUserId:true,username:true,avatarUrl:true}}}}):[];const events=await prisma.event.findMany({where:who.role==='PULSE'?{}:{organizationId:who.id},orderBy:{createdAt:'desc'},include:{organization:{select:{name:true}},maps:{orderBy:{sortOrder:'asc'},include:{map:true}},vetoSessions:{where:{archivedAt:null},orderBy:{createdAt:'desc'},select:{id:true,name:true,bestOf:true,teamAName:true,teamALogo:true,teamBName:true,teamBLogo:true,status:true,version:true,publicSharingEnabled:true,createdAt:true,teamKeys:{where:{revokedAt:null},select:{expiresAt:true}}}}}});const maps=await prisma.map.findMany({orderBy:{nameEn:'asc'}}),members=await prisma.organizationDiscordMember.findMany({where:who.role==='PULSE'?{}:{organizationId:who.id},select:{discordUserId:true,organizationId:true,username:true,avatarUrl:true}}),organizationIdsByDiscord=new Map<string,string[]>();for(const member of members)organizationIdsByDiscord.set(member.discordUserId,[...(organizationIdsByDiscord.get(member.discordUserId)||[]),member.organizationId]);const accounts=await prisma.discordAccount.findMany({where:who.role==='PULSE'?{}:{discordUserId:{in:members.map(member=>member.discordUserId)}},orderBy:{lastLoginAt:'desc'}}),accountsById=new Map(accounts.map(account=>[account.discordUserId,account])),discordIds=[...new Set([...accounts.map(account=>account.discordUserId),...members.map(member=>member.discordUserId)])],discordAccounts=discordIds.map(discordUserId=>{const account=accountsById.get(discordUserId),member=members.find(item=>item.discordUserId===discordUserId);return{discordUserId,username:account?.username||member?.username||'尚未登入',avatarUrl:account?.avatarUrl||member?.avatarUrl||null,firstLoginAt:account?.firstLoginAt||null,lastLoginAt:account?.lastLoginAt||null,loginCount:account?.loginCount||0,organizationIds:organizationIdsByDiscord.get(discordUserId)||[],isPulse:discordUserId===env.PULSE_DISCORD_USER_ID,pendingFirstLogin:!account}});res.json({role:who.role,viewer:who.role==='PULSE'?who.admin.admin.username:who.org.organization.name,organizationId:who.role==='ORGANIZATION'?who.id:null,organizations,events,maps,discordAccounts});});

  r.post('/organizations',requireCsrf(csrfRecord),async(req,res)=>{const who=(await identity(req))!;if(who.role!=='PULSE')return deny(res);const body=z.object({name:z.string().min(1).max(120),description:z.string().max(1000).optional(),expiresAt:z.string().datetime()}).parse(req.body),plain=generateAccessKey(),normalized=normalizeKey(plain);const org=await prisma.organization.create({data:{name:body.name,description:body.description,expiresAt:new Date(body.expiresAt),keys:{create:{lookupHash:lookupHash(plain),verificationHash:await hashSecret(normalized),encryptedKey:encryptSecret(plain),lastFour:normalized.slice(-4),expiresAt:new Date(body.expiresAt)}}}});await audit({action:'ORGANIZATION_CREATED',actorType:'PULSE_ADMIN',actorId:who.id,organizationId:org.id,entityType:'ORGANIZATION',entityId:org.id,ip:req.ip});res.status(201).json({organization:org,accessKey:plain});});
  r.patch('/organizations/:id',requireCsrf(csrfRecord),async(req,res)=>{const who=(await identity(req))!;if(who.role!=='PULSE')return deny(res);const body=z.object({name:z.string().min(1).max(120).optional(),status:z.enum(['ACTIVE','SUSPENDED','ARCHIVED']).optional(),expiresAt:z.string().datetime().optional()}).parse(req.body);const org=await prisma.organization.update({where:{id:String(req.params.id)},data:{...body,expiresAt:body.expiresAt?new Date(body.expiresAt):undefined}});await audit({action:'ORGANIZATION_UPDATED',actorType:'PULSE_ADMIN',actorId:who.id,organizationId:org.id,entityId:org.id,ip:req.ip,details:body});res.json(org);});
  r.post('/organizations/:id/rotate-key',requireCsrf(csrfRecord),async(req,res)=>{const who=(await identity(req))!;if(who.role!=='PULSE')return deny(res);const body=z.object({expiresAt:z.string().datetime()}).parse(req.body),plain=generateAccessKey(),normalized=normalizeKey(plain),now=new Date();await prisma.$transaction([prisma.organizationAccessKey.updateMany({where:{organizationId:String(req.params.id),revokedAt:null},data:{revokedAt:now}}),prisma.organizationAccessKey.create({data:{organizationId:String(req.params.id),lookupHash:lookupHash(plain),verificationHash:await hashSecret(normalized),encryptedKey:encryptSecret(plain),lastFour:normalized.slice(-4),expiresAt:new Date(body.expiresAt)}}),prisma.organizationSession.updateMany({where:{organizationId:String(req.params.id),revokedAt:null},data:{revokedAt:now}})]);await audit({action:'ORGANIZATION_KEY_ROTATED',actorType:'PULSE_ADMIN',actorId:who.id,organizationId:String(req.params.id),ip:req.ip,details:{lastFour:normalized.slice(-4)}});res.json({accessKey:plain});});

  r.post('/events',requireCsrf(csrfRecord),async(req,res)=>{const who=(await identity(req))!,body=eventInput.parse(req.body),organizationId=who.role==='PULSE'?body.organizationId:who.id;if(!organizationId)return res.status(400).json({error:'缺少賽事單位'});const active=await prisma.map.count({where:{id:{in:body.mapIds},enabled:true}});if(active!==body.mapIds.length)return res.status(400).json({error:'請選擇已啟用地圖'});const event=await prisma.event.create({data:{organizationId,status:'ACTIVE',name:body.name,description:body.description,logoPath:body.logoPath||null,logoUrl:body.logoUrl||null,startsAt:body.startsAt?new Date(body.startsAt):null,endsAt:body.endsAt?new Date(body.endsAt):null,themeColor:body.themeColor,defaultKeyTtlMinutes:body.defaultKeyTtlMinutes,publicSharingEnabled:body.publicSharingEnabled,maps:{create:body.mapIds.map((mapId,sortOrder)=>({mapId,sortOrder}))},vetoFlows:body.mapIds.length===7?{create:defaultVctFlows.map(flow=>({name:flow.name,stepsJson:JSON.stringify(eventFlowSteps(flow,7))}))}:undefined}});await audit({action:'EVENT_CREATED',actorType:who.role,actorId:who.id,organizationId,eventId:event.id,entityId:event.id,ip:req.ip});res.status(201).json(event);});
  r.patch('/events/:id',requireCsrf(csrfRecord),async(req,res)=>{const who=(await identity(req))!,existing=await ownsEvent(who,String(req.params.id));if(!existing)return deny(res);const body=eventInput.omit({organizationId:true,mapIds:true}).partial().parse(req.body);const event=await prisma.event.update({where:{id:existing.id},data:{...body,logoUrl:body.logoUrl||undefined,startsAt:body.startsAt?new Date(body.startsAt):undefined,endsAt:body.endsAt?new Date(body.endsAt):undefined}});await audit({action:'EVENT_UPDATED',actorType:who.role,actorId:who.id,organizationId:event.organizationId,eventId:event.id,ip:req.ip,details:body});res.json(event);});
  r.post('/events/:id/archive',requireCsrf(csrfRecord),async(req,res)=>{const who=(await identity(req))!,event=await ownsEvent(who,String(req.params.id));if(!event)return deny(res);const updated=await prisma.event.update({where:{id:event.id},data:{status:'ARCHIVED'}});await audit({action:'EVENT_ARCHIVED',actorType:who.role,actorId:who.id,organizationId:event.organizationId,eventId:event.id,ip:req.ip});res.json(updated);});

  r.post('/veto-sessions',requireCsrf(csrfRecord),async(req,res)=>{
    const who=(await identity(req))!,body=bpInput.parse(req.body),event=await ownsEvent(who,body.eventId);
    if(!event||event.deletedAt)return deny(res);
    const expiresAt=new Date(body.keyExpiresAt),keyA=generateTeamAccessKey(),keyB=generateTeamAccessKey(),overlayToken=randomToken(32),resultToken=randomToken(32);
    const [hashA,hashB]=await Promise.all([hashSecret(normalizeKey(keyA)),hashSecret(normalizeKey(keyB))]);
    const veto=await prisma.$transaction(async tx=>{
      const pool=await tx.eventMap.count({where:{eventId:event.id}});
      const flow=body.flowId?await tx.eventVetoFlow.findFirst({where:{id:body.flowId,eventId:event.id}}):null;
      if(body.flowId&&!flow)throw Object.assign(new Error('找不到此賽事的 BP 流程'),{status:400});
      if(!flow&&pool!==7)throw Object.assign(new Error('請先設定並選擇此賽事的 BP 流程'),{status:400});
      const steps=flow?eventFlowSteps({name:flow.name,steps:JSON.parse(flow.stepsJson)},pool):validateVetoSteps(body.steps?.length?body.steps:defaultStepsForBestOf(body.bestOf),pool);
      const bestOf=flow?steps.filter(step=>step.action!=='BAN').length:body.bestOf;
      return tx.vetoSession.create({data:{eventId:event.id,name:body.name,bestOf,flowName:flow?.name,status:'WAITING_FOR_TEAMS',teamAName:body.teamAName,teamALogo:body.teamALogo,teamBName:body.teamBName,teamBLogo:body.teamBLogo,mapSelectionSeconds:body.mapSelectionSeconds,sideSelectionSeconds:body.sideSelectionSeconds,overlayTheme:body.overlayTheme,publicSharingEnabled:true,
        steps:{create:steps.map(step=>({...step,resultOrder:step.resultOrder??null,customLabel:step.customLabel??null,sideSelector:step.sideSelector??null}))},
        teamKeys:{create:[{team:'TEAM_A',lookupHash:lookupHash(keyA),verificationHash:hashA,encryptedKey:encryptSecret(keyA),lastFour:normalizeKey(keyA).slice(-4),expiresAt},{team:'TEAM_B',lookupHash:lookupHash(keyB),verificationHash:hashB,encryptedKey:encryptSecret(keyB),lastFour:normalizeKey(keyB).slice(-4),expiresAt}]},
        publicTokens:{create:[{type:'OVERLAY',tokenHash:tokenHash(overlayToken),encryptedToken:encryptSecret(overlayToken),lastFour:overlayToken.slice(-4)},{type:'RESULT',tokenHash:tokenHash(resultToken),encryptedToken:encryptSecret(resultToken),lastFour:resultToken.slice(-4)}]}}});
    });
    const current=await prisma.vetoSession.findUniqueOrThrow({where:{id:veto.id}});
    await audit({action:'VETO_CREATED',actorType:who.role,actorId:who.id,organizationId:event.organizationId,eventId:event.id,vetoSessionId:veto.id,ip:req.ip,details:{bestOf:veto.bestOf,flowName:veto.flowName}});
    res.status(201).json({veto:current,teamAKey:keyA,teamBKey:keyB,overlayToken,resultToken});
  });
  r.get('/veto-sessions/:id/secrets',requireCsrf(csrfRecord),async(req,res)=>{const who=(await identity(req))!,veto=await prisma.vetoSession.findUnique({where:{id:String(req.params.id)},include:{event:true,teamKeys:{where:{revokedAt:null}},publicTokens:{where:{revokedAt:null}}}});if(!veto||!(await ownsEvent(who,veto.eventId)))return deny(res);res.set('Cache-Control','no-store').json({keys:veto.teamKeys.map(k=>({team:k.team,key:decryptSecret(k.encryptedKey),lastFour:k.lastFour,expiresAt:k.expiresAt})),tokens:veto.publicTokens.map(t=>({type:t.type,token:t.encryptedToken?decryptSecret(t.encryptedToken):null,lastFour:t.lastFour}))});});
  r.post('/veto-sessions/:id/control',requireCsrf(csrfRecord),async(req,res)=>{const who=(await identity(req))!,veto=await prisma.vetoSession.findUnique({where:{id:String(req.params.id)},include:{event:true}});if(!veto||!(await ownsEvent(who,veto.eventId)))return deny(res);const {action}=z.object({action:z.enum(['START','PAUSE','RESUME','CANCEL'])}).parse(req.body);const allowed=action==='START'&&['DRAFT','SCHEDULED'].includes(veto.status)||action==='PAUSE'&&veto.status==='ACTIVE'||action==='RESUME'&&veto.status==='PAUSED'||action==='CANCEL'&&!['COMPLETED','CANCELLED'].includes(veto.status);if(!allowed)return res.status(409).json({error:'目前狀態不允許此操作'});const status=action==='START'||action==='RESUME'?'ACTIVE':action==='PAUSE'?'PAUSED':'CANCELLED',actionDeadlineAt=status==='ACTIVE'&&veto.mapSelectionSeconds>=0?new Date(Date.now()+veto.mapSelectionSeconds*1000):null;const updated=await prisma.vetoSession.update({where:{id:veto.id},data:{status,actionDeadlineAt,version:{increment:1}}});await audit({action:`VETO_${action}`,actorType:who.role,actorId:who.id,organizationId:veto.event.organizationId,eventId:veto.eventId,vetoSessionId:veto.id,ip:req.ip});io.to(`veto:${veto.id}`).emit('veto:changed',{version:updated.version});res.json(updated);});
  r.get('/veto-sessions/:id/snapshot',async(req,res)=>{const who=(await identity(req))!,veto=await prisma.vetoSession.findUnique({where:{id:String(req.params.id)}});if(!veto||!(await ownsEvent(who,veto.eventId)))return deny(res);res.json(await vetoSnapshot(veto.id));});
  r.put('/veto-sessions/:id/map-results',requireCsrf(csrfRecord),async(req,res)=>{const who=(await identity(req))!,id=String(req.params.id),veto=await prisma.vetoSession.findUnique({where:{id},include:{event:true}});if(!veto||!(await ownsEvent(who,veto.eventId)))return deny(res);const itemSchema=z.object({actionId:z.string(),teamAScore:z.number().int().min(0).max(99),teamBScore:z.number().int().min(0).max(99),winner:z.enum(['TEAM_A','TEAM_B']).nullable(),isNextMap:z.boolean().default(false)}),items=z.array(itemSchema).max(5).refine(values=>new Set(values.map(value=>value.actionId)).size===values.length,'地圖結果不得重複').refine(values=>values.filter(value=>value.isNextMap&&!value.winner).length<=1,'最多只能設定一張下一張地圖').parse(req.body?.results);const actions=await prisma.vetoAction.findMany({where:{vetoSessionId:id,id:{in:items.map(item=>item.actionId)},action:{in:['PICK','DECIDER']}},include:{map:true,step:true}});if(actions.length!==items.length)return res.status(400).json({error:'包含無效或不可設定比分的地圖'});for(const item of items){if(item.winner&&item.teamAScore===item.teamBScore)return res.status(400).json({error:'已有勝方時，雙方比分不可相同'});if(item.winner==='TEAM_A'&&item.teamAScore<item.teamBScore||item.winner==='TEAM_B'&&item.teamBScore<item.teamAScore)return res.status(400).json({error:'勝方的比分不可低於敗方'})}await prisma.$transaction(async tx=>{await tx.mapResult.updateMany({where:{vetoSessionId:id,isNextMap:true},data:{isNextMap:false}});for(const item of items){const isNextMap=item.winner?false:item.isNextMap;await tx.mapResult.upsert({where:{vetoActionId:item.actionId},create:{vetoSessionId:id,vetoActionId:item.actionId,teamAScore:item.teamAScore,teamBScore:item.teamBScore,winner:item.winner,isNextMap,completedAt:item.winner?new Date():null},update:{teamAScore:item.teamAScore,teamBScore:item.teamBScore,winner:item.winner,isNextMap,completedAt:item.winner?new Date():null}})}});await audit({action:'MAP_RESULTS_UPDATED',actorType:who.role,actorId:who.id,organizationId:veto.event.organizationId,eventId:veto.eventId,vetoSessionId:id,entityType:'VETO_SESSION',entityId:id,ip:req.ip,details:{maps:items.map(item=>({actionId:item.actionId,teamAScore:item.teamAScore,teamBScore:item.teamBScore,winner:item.winner,isNextMap:item.winner?false:item.isNextMap}))}});const snap=await vetoSnapshot(id);io.to(`veto:${id}`).emit('veto:changed',{mapResults:true});io.to(`veto:${id}`).emit('state_changed',overlayDto(snap));res.json(snap)});
  r.put('/veto-sessions/:id/map-results/:actionId',requireCsrf(csrfRecord),async(req,res)=>{const who=(await identity(req))!,id=String(req.params.id),actionId=String(req.params.actionId),veto=await prisma.vetoSession.findUnique({where:{id},include:{event:true}});if(!veto||!(await ownsEvent(who,veto.eventId)))return deny(res);const body=z.object({teamAScore:z.number().int().min(0).max(99),teamBScore:z.number().int().min(0).max(99),winner:z.enum(['TEAM_A','TEAM_B']).nullable(),isNextMap:z.boolean().default(false)}).parse(req.body);const action=await prisma.vetoAction.findFirst({where:{id:actionId,vetoSessionId:id},include:{map:true,step:true}});if(!action||action.action==='BAN')return res.status(404).json({error:'找不到可設定比分的地圖'});if(body.winner&&body.teamAScore===body.teamBScore)return res.status(400).json({error:'已有勝方時，雙方比分不可相同'});if(body.winner==='TEAM_A'&&body.teamAScore<body.teamBScore||body.winner==='TEAM_B'&&body.teamBScore<body.teamAScore)return res.status(400).json({error:'勝方的比分不可低於敗方'});const isNextMap=body.winner?false:body.isNextMap;await prisma.$transaction(async tx=>{if(isNextMap)await tx.mapResult.updateMany({where:{vetoSessionId:id,isNextMap:true},data:{isNextMap:false}});await tx.mapResult.upsert({where:{vetoActionId:action.id},create:{vetoSessionId:id,vetoActionId:action.id,teamAScore:body.teamAScore,teamBScore:body.teamBScore,winner:body.winner,isNextMap,completedAt:body.winner?new Date():null},update:{teamAScore:body.teamAScore,teamBScore:body.teamBScore,winner:body.winner,isNextMap,completedAt:body.winner?new Date():null}})});await audit({action:'MAP_RESULT_UPDATED',actorType:who.role,actorId:who.id,organizationId:veto.event.organizationId,eventId:veto.eventId,vetoSessionId:id,entityType:'VETO_ACTION',entityId:action.id,ip:req.ip,details:{map:action.map.nameEn,step:action.step.stepNumber,teamAScore:body.teamAScore,teamBScore:body.teamBScore,winner:body.winner,isNextMap}});const snap=await vetoSnapshot(id);io.to(`veto:${id}`).emit('veto:changed',{mapResult:true});io.to(`veto:${id}`).emit('state_changed',overlayDto(snap));res.json(snap)});
  r.post('/maps/sync',requireCsrf(csrfRecord),async(req,res)=>{const who=(await identity(req))!;if(who.role!=='PULSE')return deny(res);const result=await syncValorantMaps();await audit({action:'MAPS_SYNCHRONIZED',actorType:'PULSE_ADMIN',actorId:who.id,ip:req.ip,details:{count:result.data.length}});res.json({count:result.data.length,syncedAt:result.syncedAt})});
  r.patch('/maps/:id',requireCsrf(csrfRecord),async(req,res)=>{const who=(await identity(req))!;if(who.role!=='PULSE')return deny(res);const enabled=z.object({enabled:z.boolean()}).parse(req.body).enabled,map=await prisma.map.update({where:{id:String(req.params.id)},data:{enabled}});await audit({action:'MAP_STATUS_CHANGED',actorType:'PULSE_ADMIN',actorId:who.id,entityType:'MAP',entityId:map.id,ip:req.ip,details:{enabled}});res.json(map)});
  r.put('/events/:id/maps',requireCsrf(csrfRecord),async(req,res)=>{
    const who=(await identity(req))!,event=await ownsEvent(who,String(req.params.id));if(!event||event.deletedAt)return deny(res);
    const mapIds=mapPoolInput.parse(req.body?.mapIds);
    await prisma.$transaction(async tx=>{
      const active=await tx.map.count({where:{id:{in:mapIds},enabled:true}});
      if(active!==mapIds.length)throw Object.assign(new Error('請選擇已啟用地圖'),{status:400});
      const previousMaps=await tx.eventMap.findMany({where:{eventId:event.id},orderBy:{sortOrder:'asc'}});
      if(previousMaps.length===mapIds.length&&previousMaps.every(map=>mapIds.includes(map.mapId)))return;
      if(await tx.vetoSession.count({where:{eventId:event.id}}))throw Object.assign(new Error('賽事已有 BP，不能直接修改地圖池'),{status:409});
      if(previousMaps.length!==mapIds.length&&await tx.eventVetoFlow.count({where:{eventId:event.id}}))throw Object.assign(new Error('已有 BP 流程，請先刪除流程再變更地圖數量'),{status:409});
      await tx.eventMap.deleteMany({where:{eventId:event.id}});
      await tx.eventMap.createMany({data:mapIds.map((mapId,sortOrder)=>({eventId:event.id,mapId,sortOrder}))});
    });
    await audit({action:'EVENT_MAP_POOL_UPDATED',actorType:who.role,actorId:who.id,organizationId:event.organizationId,eventId:event.id,ip:req.ip,details:{mapIds}});res.json({ok:true});
  });
  r.post('/veto-sessions/:id/rotate-team-key',requireCsrf(csrfRecord),async(req,res)=>{const who=(await identity(req))!,id=String(req.params.id),veto=await prisma.vetoSession.findUnique({where:{id}});if(!veto||!(await ownsEvent(who,veto.eventId)))return deny(res);const body=z.object({team:z.enum(['TEAM_A','TEAM_B']),expiresAt:z.string().datetime()}).parse(req.body),plain=generateTeamAccessKey(),normal=normalizeKey(plain),now=new Date();await prisma.$transaction([prisma.teamAccessKey.updateMany({where:{vetoSessionId:id,team:body.team,revokedAt:null},data:{revokedAt:now}}),prisma.teamSession.updateMany({where:{vetoSessionId:id,team:body.team,revokedAt:null},data:{revokedAt:now}}),prisma.teamAccessKey.create({data:{vetoSessionId:id,team:body.team,lookupHash:lookupHash(plain),verificationHash:await hashSecret(normal),encryptedKey:encryptSecret(plain),lastFour:normal.slice(-4),expiresAt:new Date(body.expiresAt)}})]);await audit({action:'TEAM_KEY_ROTATED',actorType:who.role,actorId:who.id,vetoSessionId:id,ip:req.ip,details:{team:body.team,lastFour:normal.slice(-4)}});res.json({key:plain})});
  r.post('/veto-sessions/:id/rotate-public-token',requireCsrf(csrfRecord),async(req,res)=>{const who=(await identity(req))!,id=String(req.params.id),veto=await prisma.vetoSession.findUnique({where:{id}});if(!veto||!(await ownsEvent(who,veto.eventId)))return deny(res);const type=z.object({type:z.enum(['OVERLAY','RESULT'])}).parse(req.body).type,plain=randomToken(32),now=new Date();await prisma.$transaction([prisma.publicToken.updateMany({where:{vetoSessionId:id,type,revokedAt:null},data:{revokedAt:now}}),prisma.publicToken.create({data:{vetoSessionId:id,type,tokenHash:tokenHash(plain),encryptedToken:encryptSecret(plain),lastFour:plain.slice(-4)}})]);await audit({action:`${type}_TOKEN_ROTATED`,actorType:who.role,actorId:who.id,vetoSessionId:id,ip:req.ip,details:{lastFour:plain.slice(-4)}});res.json({token:plain})});
  r.patch('/veto-sessions/:id/public',requireCsrf(csrfRecord),async(req,res)=>{const who=(await identity(req))!,id=String(req.params.id),veto=await prisma.vetoSession.findUnique({where:{id}});if(!veto||!(await ownsEvent(who,veto.eventId)))return deny(res);z.object({enabled:z.boolean()}).parse(req.body);const updated=await prisma.vetoSession.update({where:{id},data:{publicSharingEnabled:true}});res.json(updated)});
  r.post('/veto-sessions/:id/admin-side',requireCsrf(csrfRecord),async(req,res)=>{const who=(await identity(req))!,id=String(req.params.id),veto=await prisma.vetoSession.findUnique({where:{id},include:{steps:{orderBy:{stepNumber:'asc'}},event:true}});if(!veto||!(await ownsEvent(who,veto.eventId)))return deny(res);const body=z.object({selector:z.enum(['TEAM_A','TEAM_B']),side:z.enum(['ATTACK','DEFENSE']),reason:z.string().min(5).max(500),expectedVersion:z.number().int()}).parse(req.body),step=veto.steps[veto.currentStep];if(!step||step.sideSelectionMode!=='ADMIN_SELECTS')return res.status(409).json({error:'目前步驟不是管理員選邊'});await submitSide({sessionId:id,team:body.selector,side:body.side,expectedVersion:body.expectedVersion,adminOverride:true,reason:body.reason});await audit({action:'SIDE_ADMIN_OVERRIDE',actorType:who.role,actorId:who.id,organizationId:veto.event.organizationId,eventId:veto.eventId,vetoSessionId:id,ip:req.ip,details:{selector:body.selector,side:body.side,reason:body.reason}});io.to(`veto:${id}`).emit('veto:changed',{adminOverride:true});res.json(await vetoSnapshot(id))});  r.post('/veto-sessions/:id/reset',requireCsrf(csrfRecord),async(req,res)=>{const who=(await identity(req))!,id=String(req.params.id),reason=z.object({reason:z.string().min(5).max(500)}).parse(req.body).reason,veto=await prisma.vetoSession.findUnique({where:{id},include:{event:true}});if(!veto||!(await ownsEvent(who,veto.eventId)))return deny(res);await prisma.$transaction([prisma.mapSideSelection.deleteMany({where:{vetoSessionId:id}}),prisma.vetoAction.deleteMany({where:{vetoSessionId:id}}),prisma.teamSession.updateMany({where:{vetoSessionId:id,revokedAt:null},data:{revokedAt:new Date()}}),prisma.vetoSession.update({where:{id},data:{status:'WAITING_FOR_TEAMS',currentStep:0,completedAt:null,coinTossWinner:null,coinTossAt:null,teamAReadyAt:null,teamBReadyAt:null,actionDeadlineAt:null,version:{increment:1}}})]);await audit({action:'VETO_RESET',actorType:who.role,actorId:who.id,organizationId:veto.event.organizationId,eventId:veto.eventId,vetoSessionId:id,ip:req.ip,details:{reason}});io.to(`veto:${id}`).emit('veto:changed',{reset:true});res.json({ok:true})});
  r.post('/backup',requireCsrf(csrfRecord),async(req,res)=>{const who=(await identity(req))!;if(who.role!=='PULSE')return deny(res);const {createBackup}=await import('../services/backup.js'),file=await createBackup('manual');await audit({action:'BACKUP_CREATED',actorType:'PULSE_ADMIN',actorId:who.id,ip:req.ip,details:{file:file.split(/[\\/]/).pop()}});res.json({ok:true,file:file.split(/[\\/]/).pop()})});
  r.get('/audit',async(req,res)=>{const who=(await identity(req))!;if(who.role==='PULSE')return res.json(await prisma.auditLog.findMany({orderBy:{createdAt:'desc'},take:500}));const visibleActions=['EVENT_CREATED','EVENT_UPDATED','EVENT_ARCHIVED','EVENT_MAP_POOL_UPDATED','VETO_CREATED','VETO_START','VETO_PAUSE','VETO_RESUME','VETO_CANCEL','VETO_BAN','VETO_PICK','VETO_DECIDER','SIDE_SELECTED','COIN_TOSS','VETO_COMPLETED','MAP_RESULTS_UPDATED','MAP_RESULT_UPDATED','RESULT_PUBLIC_STATUS_CHANGED'];res.json(await prisma.auditLog.findMany({where:{organizationId:who.id,action:{in:visibleActions}},select:{createdAt:true,action:true,actorType:true},orderBy:{createdAt:'desc'},take:200}));});
  r.delete('/veto-sessions/:id',requireCsrf(csrfRecord),async(req,res)=>{const who=(await identity(req))!,id=String(req.params.id),veto=await prisma.vetoSession.findUnique({where:{id},include:{event:true}});if(!veto||!(await ownsEvent(who,veto.eventId)))return deny(res);if(veto.archivedAt)return res.json({ok:true});const now=new Date();await prisma.$transaction([prisma.teamSession.updateMany({where:{vetoSessionId:id,revokedAt:null},data:{revokedAt:now}}),prisma.teamAccessKey.updateMany({where:{vetoSessionId:id,revokedAt:null},data:{revokedAt:now}}),prisma.publicToken.updateMany({where:{vetoSessionId:id,revokedAt:null},data:{revokedAt:now}}),prisma.vetoSession.update({where:{id},data:{archivedAt:now,status:veto.status==='COMPLETED'?'COMPLETED':'CANCELLED',version:{increment:1}}})]);await audit({action:'VETO_ARCHIVED',actorType:who.role,actorId:who.id,organizationId:veto.event.organizationId,eventId:veto.eventId,vetoSessionId:id,ip:req.ip,details:{previousStatus:veto.status}});io.to(`veto:${id}`).emit('veto:changed',{archived:true});res.json({ok:true})});
  r.get('/organizations/:id/secret',requireCsrf(csrfRecord),async(req,res)=>{const who=(await identity(req))!;if(who.role!=='PULSE')return deny(res);const organization=await prisma.organization.findUnique({where:{id:String(req.params.id)},include:{keys:{where:{revokedAt:null},orderBy:{createdAt:'desc'},take:1}}});if(!organization)return res.status(404).json({error:'找不到賽事單位'});const key=organization.keys[0];if(!key)return res.status(404).json({error:'此賽事單位沒有有效金鑰'});res.set('Cache-Control','no-store').json({name:organization.name,key:decryptSecret(key.encryptedKey),lastFour:key.lastFour,expiresAt:key.expiresAt})});
  r.get('/hierarchy',async(req,res)=>{
    const who=(await identity(req))!,organizationWhere=who.role==='PULSE'?{deletedAt:null}:{id:who.id,deletedAt:null};
    const organizations=await prisma.organization.findMany({where:organizationWhere,orderBy:{createdAt:'desc'},include:{discordMembers:true,events:{where:{deletedAt:null},orderBy:{createdAt:'desc'},include:{maps:{orderBy:{sortOrder:'asc'},include:{map:true}},vetoSessions:{where:{deletedAt:null},orderBy:{createdAt:'desc'},include:{teamKeys:{where:{revokedAt:null},select:{expiresAt:true}}}}}}}});
    const trash=who.role==='PULSE'?{
      organizations:await prisma.organization.findMany({where:{deletedAt:{not:null}},orderBy:{deletedAt:'desc'}}),
      events:await prisma.event.findMany({where:{deletedAt:{not:null},organization:{deletedAt:null}},include:{organization:{select:{name:true}}},orderBy:{deletedAt:'desc'}}),
      vetoSessions:await prisma.vetoSession.findMany({where:{deletedAt:{not:null},event:{deletedAt:null,organization:{deletedAt:null}}},include:{event:{select:{name:true}}},orderBy:{deletedAt:'desc'}})
    }:{
      organizations:[],
      events:await prisma.event.findMany({where:{organizationId:who.id,deletedAt:{not:null}},orderBy:{deletedAt:'desc'}}),
      vetoSessions:await prisma.vetoSession.findMany({where:{event:{organizationId:who.id,deletedAt:null},deletedAt:{not:null}},include:{event:{select:{name:true}}},orderBy:{deletedAt:'desc'}})
    };
    const members=await prisma.organizationDiscordMember.findMany({where:who.role==='PULSE'?{}:{organizationId:who.id},select:{discordUserId:true,organizationId:true,username:true,avatarUrl:true}}),organizationIdsByDiscord=new Map<string,string[]>();for(const member of members)organizationIdsByDiscord.set(member.discordUserId,[...(organizationIdsByDiscord.get(member.discordUserId)||[]),member.organizationId]);
    const accounts=await prisma.discordAccount.findMany({where:who.role==='PULSE'?{}:{discordUserId:{in:members.map(member=>member.discordUserId)}},orderBy:{lastLoginAt:'desc'}}),accountsById=new Map(accounts.map(account=>[account.discordUserId,account])),discordIds=[...new Set([...accounts.map(account=>account.discordUserId),...members.map(member=>member.discordUserId)])];
    const discordAccounts=discordIds.map(discordUserId=>{const account=accountsById.get(discordUserId),member=members.find(item=>item.discordUserId===discordUserId);return{discordUserId,username:account?.username||member?.username||'尚未登入',avatarUrl:account?.avatarUrl||member?.avatarUrl||null,firstLoginAt:account?.firstLoginAt||null,lastLoginAt:account?.lastLoginAt||null,loginCount:account?.loginCount||0,organizationIds:organizationIdsByDiscord.get(discordUserId)||[],isPulse:discordUserId===env.PULSE_DISCORD_USER_ID,pendingFirstLogin:!account}});
    res.json({role:who.role,viewer:who.role==='PULSE'?who.admin.admin.username:who.org.organization.name,viewerAvatar:who.role==='PULSE'?'/branding/PulseVeto_MainIcon.png':who.org.organization.iconPath,organizations,trash,maps:await prisma.map.findMany({orderBy:{nameEn:'asc'}}),discordAccounts});
  });
  r.patch('/events/:id/status',requireCsrf(csrfRecord),async(req,res)=>{const who=(await identity(req))!,event=await ownsEvent(who,String(req.params.id));if(!event||event.deletedAt)return deny(res);const status=z.enum(['DRAFT','ACTIVE','ARCHIVED']).parse(req.body?.status),updated=await prisma.event.update({where:{id:event.id},data:{status}});await audit({action:'EVENT_STATUS_CHANGED',actorType:who.role,actorId:who.id,organizationId:event.organizationId,eventId:event.id,ip:req.ip,details:{status}});res.json(updated)});
  r.delete('/organizations/:id',requireCsrf(csrfRecord),async(req,res)=>{const who=(await identity(req))!;if(who.role!=='PULSE')return deny(res);const item=await deleteOrganization(String(req.params.id));if(!item)return res.status(404).json({error:'找不到賽事單位'});await audit({action:'ORGANIZATION_DELETED',actorType:'PULSE_ADMIN',actorId:who.id,organizationId:item.id,ip:req.ip});res.json({ok:true,purgeAt:item.purgeAt})});
  r.delete('/events/:id',requireCsrf(csrfRecord),async(req,res)=>{const who=(await identity(req))!,event=await ownsEvent(who,String(req.params.id));if(!event)return deny(res);const item=await deleteEvent(event.id);await audit({action:'EVENT_DELETED',actorType:who.role,actorId:who.id,organizationId:event.organizationId,eventId:event.id,ip:req.ip});res.json({ok:true,purgeAt:item?.purgeAt})});
  r.delete('/veto-sessions/:id/recycle',requireCsrf(csrfRecord),async(req,res)=>{const who=(await identity(req))!,veto=await prisma.vetoSession.findUnique({where:{id:String(req.params.id)},include:{event:true}});if(!veto||!(await ownsEvent(who,veto.eventId)))return deny(res);const item=await deleteVetoSession(veto.id);await audit({action:'VETO_DELETED',actorType:who.role,actorId:who.id,organizationId:veto.event.organizationId,eventId:veto.eventId,vetoSessionId:veto.id,ip:req.ip});io.to(`veto:${veto.id}`).emit('veto:changed',{deleted:true});res.json({ok:true,purgeAt:item?.purgeAt})});
  r.post('/trash/organizations/:id/restore',requireCsrf(csrfRecord),async(req,res)=>{const who=(await identity(req))!;if(who.role!=='PULSE')return deny(res);const item=await restoreOrganization(String(req.params.id));if(!item)return res.status(404).json({error:'找不到賽事單位'});await audit({action:'ORGANIZATION_RESTORED',actorType:'PULSE_ADMIN',actorId:who.id,organizationId:item.id,ip:req.ip});res.json(item)});
  r.post('/trash/events/:id/restore',requireCsrf(csrfRecord),async(req,res)=>{const who=(await identity(req))!,event=await prisma.event.findUnique({where:{id:String(req.params.id)}});if(!event||who.role!=='PULSE'&&event.organizationId!==who.id)return deny(res);const item=await restoreEvent(event.id);await audit({action:'EVENT_RESTORED',actorType:who.role,actorId:who.id,organizationId:event.organizationId,eventId:event.id,ip:req.ip});res.json(item)});
  r.post('/trash/veto-sessions/:id/restore',requireCsrf(csrfRecord),async(req,res)=>{const who=(await identity(req))!,veto=await prisma.vetoSession.findUnique({where:{id:String(req.params.id)},include:{event:true}});if(!veto||who.role!=='PULSE'&&veto.event.organizationId!==who.id)return deny(res);const item=await restoreVetoSession(veto.id);await audit({action:'VETO_RESTORED',actorType:who.role,actorId:who.id,organizationId:veto.event.organizationId,eventId:veto.eventId,vetoSessionId:veto.id,ip:req.ip});res.json(item)});
  return r;
}
