import {beforeAll,afterAll,describe,expect,it} from 'vitest';
import request from 'supertest';
process.env.NODE_ENV='test';process.env.DATABASE_URL='file:../storage/database/integration.db';process.env.SESSION_SECRET='integration-session-secret-at-least-32-chars';process.env.KEY_ENCRYPTION_SECRET='integration-encryption-secret-32-chars';process.env.PUBLIC_BASE_URL='http://localhost:3000';process.env.DISCORD_CLIENT_ID='test-client';process.env.DISCORD_CLIENT_SECRET='test-secret';process.env.DISCORD_REDIRECT_URI='http://localhost:3000/api/auth/discord/callback';
let app:any,prisma:any,hashSecret:any,agent:any,csrf='';
const csrfFrom=(response:any)=>decodeURIComponent((response.headers['set-cookie'] as string[]).find(x=>x.startsWith('veto_csrf='))!.split(';')[0]!.split('=')[1]!);
beforeAll(async()=>{({app}=await import('../../src/server.js'));({prisma}=await import('../../src/lib/db.js'));({hashSecret}=await import('../../src/lib/security.js'));await prisma.adminUser.create({data:{username:'pulse-test',passwordHash:await hashSecret('integration-password')}});for(let i=1;i<=7;i++)await prisma.map.create({data:{id:`map-${i}`,nameEn:`Map ${i}`,nameZhTw:`地圖 ${i}`,enabled:true}});agent=request.agent(app);const login=await agent.post('/api/auth/pulse').send({identifier:'pulsemilotw',password:'integration-password'});expect(login.status).toBe(200);csrf=csrfFrom(login)});
afterAll(async()=>{await prisma.$disconnect()});
describe('management authorization flow',()=>{
  it('rejects mutation without csrf',async()=>{expect((await agent.post('/api/manage/organizations').send({})).status).toBe(403)});
  it('does not expose legacy management pages without authentication',async()=>{for(const path of ['/manage.html','/team.html','/admin.html','/admin-home.html','/key-admin.html'])expect((await request(app).get(path)).status).toBe(404);expect((await request(app).get('/admin')).status).toBe(302);expect((await request(app).get('/api/manage/context')).status).toBe(401)});
  it('makes Discord scope cookies available to the scope page',async()=>{const oauthAgent=request.agent(app),start=await oauthAgent.get('/api/auth/discord/start');expect(start.headers.location).toBeTruthy();const state=new URL(start.headers.location!).searchParams.get('state'),originalFetch=global.fetch;global.fetch=(async(url:any)=>String(url).includes('/oauth2/token')?new Response(JSON.stringify({access_token:'test-token',token_type:'Bearer'}),{status:200,headers:{'content-type':'application/json'}}):new Response(JSON.stringify({id:process.env.PULSE_DISCORD_USER_ID||'1456945476933914626',username:'Pulse Admin',global_name:null,avatar:null}),{status:200,headers:{'content-type':'application/json'}})) as typeof fetch;try{const callback=await oauthAgent.get('/api/auth/discord/callback').query({code:'test-code',state});expect(callback.status).toBe(302);expect(callback.headers.location).toBe('/auth/scope');const cookies=callback.headers['set-cookie'] as unknown as string[];expect(cookies.find(value=>value.startsWith('veto_discord_choice='))).toContain('Path=/');expect(cookies.find(value=>value.startsWith('veto_discord_choice_csrf='))).toContain('Path=/');expect((await oauthAgent.get('/auth/scope')).status).toBe(200)}finally{global.fetch=originalFetch}});
  it('invalidates disabled administrators and expired organizations immediately',async()=>{const admin=await prisma.adminUser.findFirstOrThrow();await prisma.adminUser.update({where:{id:admin.id},data:{disabledAt:new Date()}});expect((await agent.get('/api/manage/context')).status).toBe(401);await prisma.adminUser.update({where:{id:admin.id},data:{disabledAt:null}});const expiresAt=new Date(Date.now()+86400000).toISOString(),org=await agent.post('/api/manage/organizations').set('x-csrf-token',csrf).send({name:'Session expiry organization',expiresAt}),orgAgent=request.agent(app),login=await orgAgent.post('/api/auth/organization').send({key:org.body.accessKey});expect(login.status).toBe(200);await prisma.organization.update({where:{id:org.body.organization.id},data:{expiresAt:new Date(Date.now()-1000)}});expect((await orgAgent.get('/api/manage/context')).status).toBe(401)});
  it('automatically creates the Bo5 decider after the fourth Pick side selection',async()=>{
    const {defaultStepsForBestOf}=await import('../../src/domain/veto.js');
    const {submitSide}=await import('../../src/services/veto-service.js');
    const organization=await prisma.organization.create({data:{name:'Bo5 regression organization'}});
    const event=await prisma.event.create({data:{organizationId:organization.id,name:'Bo5 regression event',maps:{create:Array.from({length:7},(_,index)=>({mapId:`map-${index+1}`,sortOrder:index}))}}});
    const session=await prisma.vetoSession.create({data:{eventId:event.id,name:'Bo5 regression',bestOf:5,status:'WAITING_FOR_SIDE_SELECTION',currentStep:5,teamAName:'Alpha',teamBName:'Bravo',steps:{create:defaultStepsForBestOf(5).map(step=>({...step,resultOrder:step.resultOrder??null,customLabel:step.customLabel??null,sideSelector:step.sideSelector??null}))}}});
    const steps=await prisma.vetoStep.findMany({where:{vetoSessionId:session.id},orderBy:{stepNumber:'asc'}});
    for(let index=0;index<6;index++)await prisma.vetoAction.create({data:{vetoSessionId:session.id,vetoStepId:steps[index].id,mapId:`map-${index+1}`,actor:steps[index].actor,action:steps[index].action,createdAt:new Date(Date.now()-6000+index*1000)}});
    const advanced=await submitSide({sessionId:session.id,team:'TEAM_A',side:'ATTACK',expectedVersion:0});
    expect(advanced).toMatchObject({complete:false,autoDecider:true});
    const waiting=await prisma.vetoSession.findUniqueOrThrow({where:{id:session.id},include:{steps:{orderBy:{stepNumber:'asc'}},actions:{orderBy:{createdAt:'asc'}}}});
    expect(waiting.status).toBe('WAITING_FOR_SIDE_SELECTION');
    expect(waiting.actions.at(-1)).toMatchObject({action:'DECIDER',actor:'SYSTEM',mapId:'map-7'});
    expect(await prisma.randomConfirmation.findFirst({where:{vetoActionId:waiting.actions.at(-1)!.id}})).toBeNull();
    expect(waiting.steps[waiting.currentStep].sideSelector).toBe('TEAM_B');
    await expect(submitSide({sessionId:session.id,team:'TEAM_A',side:'DEFENSE',expectedVersion:1})).rejects.toMatchObject({status:403});
    await expect(submitSide({sessionId:session.id,team:'TEAM_B',side:'DEFENSE',expectedVersion:1})).resolves.toMatchObject({complete:true});
  });
  it('securely draws system maps and assigns random sides through Decider',async()=>{
    const {advanceAutomaticSteps,confirmRandomResult}=await import('../../src/services/veto-service.js');
    const organization=await prisma.organization.create({data:{name:'Random flow organization'}});
    const event=await prisma.event.create({data:{organizationId:organization.id,name:'Random flow event',maps:{create:Array.from({length:2},(_,index)=>({mapId:`map-${index+1}`,sortOrder:index}))}}});
    const session=await prisma.vetoSession.create({data:{eventId:event.id,name:'Random flow',bestOf:2,status:'ACTIVE',teamAName:'Alpha',teamBName:'Bravo',steps:{create:[
      {stepNumber:1,actor:'SYSTEM',action:'PICK',resultOrder:1,sideSelectionMode:'RANDOM'},
      {stepNumber:2,actor:'SYSTEM',action:'DECIDER',resultOrder:2,sideSelectionMode:'RANDOM'},
    ]}}});
    await expect(advanceAutomaticSteps(session.id,0)).resolves.toMatchObject({advanced:true,complete:false,autoDecider:false});
    await expect(confirmRandomResult({sessionId:session.id,team:'TEAM_A',expectedVersion:1})).resolves.toMatchObject({advanced:false});
    await expect(confirmRandomResult({sessionId:session.id,team:'TEAM_B',expectedVersion:2})).resolves.toMatchObject({advanced:true,complete:false});
    await expect(confirmRandomResult({sessionId:session.id,team:'TEAM_A',expectedVersion:3})).resolves.toMatchObject({advanced:false});
    await expect(confirmRandomResult({sessionId:session.id,team:'TEAM_B',expectedVersion:4})).resolves.toMatchObject({advanced:true,complete:true});
    const completed=await prisma.vetoSession.findUniqueOrThrow({where:{id:session.id},include:{actions:{include:{sideSelection:true,randomConfirmation:true}}}});
    expect(completed.status).toBe('COMPLETED');expect(completed.actions).toHaveLength(2);expect(new Set(completed.actions.map((action:any)=>action.mapId)).size).toBe(2);
    for(const action of completed.actions)expect(action.sideSelection).toMatchObject({selector:'TEAM_A',isDecider:action.action==='DECIDER'});
    expect(completed.actions.every((action:any)=>action.sideSelection.selectorSide!==action.sideSelection.opponentSide)).toBe(true);expect(completed.actions.every((action:any)=>action.randomConfirmation.teamAConfirmedAt&&action.randomConfirmation.teamBConfirmedAt)).toBe(true);
  });
  it('turns expired map and side choices into secure draws with the responsible team pre-confirmed',async()=>{
    const {processVetoTimeout,confirmRandomResult}=await import('../../src/services/veto-service.js');
    const organization=await prisma.organization.create({data:{name:'Timeout organization'}}),event=await prisma.event.create({data:{organizationId:organization.id,name:'Timeout event',maps:{create:[{mapId:'map-1',sortOrder:0},{mapId:'map-2',sortOrder:1}]}}});
    const mapTimeout=await prisma.vetoSession.create({data:{eventId:event.id,name:'Map timeout',teamAName:'Alpha',teamBName:'Bravo',status:'ACTIVE',mapSelectionSeconds:5,actionDeadlineAt:new Date(Date.now()-1000),steps:{create:{stepNumber:1,actor:'TEAM_A',action:'BAN',sideSelectionMode:'NONE'}}}});
    await expect(processVetoTimeout(mapTimeout.id)).resolves.toMatchObject({team:'TEAM_A',kind:'MAP'});
    let expired=await prisma.vetoSession.findUniqueOrThrow({where:{id:mapTimeout.id},include:{actions:{include:{randomConfirmation:true}}}});expect(expired.status).toBe('WAITING_FOR_RANDOM_CONFIRMATION');expect(expired.actions[0]).toMatchObject({actor:'TEAM_A',timeoutRandom:true});expect(expired.actions[0].randomConfirmation).toMatchObject({teamAConfirmedAt:expect.any(Date),teamBConfirmedAt:null});
    await expect(confirmRandomResult({sessionId:mapTimeout.id,team:'TEAM_B',expectedVersion:1})).resolves.toMatchObject({complete:true});
    const sideTimeout=await prisma.vetoSession.create({data:{eventId:event.id,name:'Side timeout',teamAName:'Alpha',teamBName:'Bravo',status:'WAITING_FOR_SIDE_SELECTION',sideSelectionSeconds:5,actionDeadlineAt:new Date(Date.now()-1000),steps:{create:{stepNumber:1,actor:'TEAM_A',action:'PICK',resultOrder:1,sideSelectionMode:'OPPONENT_SELECTS',sideSelector:'TEAM_B'}}}}),sideStep=await prisma.vetoStep.findFirstOrThrow({where:{vetoSessionId:sideTimeout.id}});
    await prisma.vetoAction.create({data:{vetoSessionId:sideTimeout.id,vetoStepId:sideStep.id,mapId:'map-1',actor:'TEAM_A',action:'PICK'}});
    await expect(processVetoTimeout(sideTimeout.id)).resolves.toMatchObject({team:'TEAM_B',kind:'SIDE'});
    expired=await prisma.vetoSession.findUniqueOrThrow({where:{id:sideTimeout.id},include:{actions:{include:{sideSelection:true,randomConfirmation:true}}}});expect(expired.actions[0]).toMatchObject({actor:'TEAM_A',timeoutRandom:true});expect(expired.actions[0].sideSelection?.selector).toBe('TEAM_B');expect(expired.actions[0].randomConfirmation).toMatchObject({teamAConfirmedAt:null,teamBConfirmedAt:expect.any(Date)});
    await expect(confirmRandomResult({sessionId:sideTimeout.id,team:'TEAM_A',expectedVersion:1})).resolves.toMatchObject({complete:true});
  });
  it('creates a Match BP successfully from a shortened random flow',async()=>{
    const expiresAt=new Date(Date.now()+86400000).toISOString(),organization=await agent.post('/api/manage/organizations').set('x-csrf-token',csrf).send({name:'Random BP API organization',expiresAt});
    const event=await agent.post('/api/manage/events').set('x-csrf-token',csrf).send({organizationId:organization.body.organization.id,name:'Random BP API event',themeColor:'#5865f2',defaultKeyTtlMinutes:1440,publicSharingEnabled:false,mapIds:['map-1','map-2','map-3']});
    const flow=await agent.post(`/api/manage/events/${event.body.id}/flows`).set('x-csrf-token',csrf).send({name:'Flexible random',steps:[{actor:'SYSTEM',action:'PICK',sideSelector:'RANDOM'},{actor:'SYSTEM',action:'DECIDER',sideSelector:'RANDOM'}]});
    expect(flow.status).toBe(201);
    const match=await agent.post('/api/manage/veto-sessions').set('x-csrf-token',csrf).send({eventId:event.body.id,flowId:flow.body.id,name:'Random match',teamAName:'Alpha',teamBName:'Bravo',keyExpiresAt:expiresAt});
    expect(match.status).toBe(201);expect(match.body.veto).toMatchObject({status:'WAITING_FOR_TEAMS',bestOf:2,flowName:'Flexible random'});
    const teamA=request.agent(app),teamB=request.agent(app),loginA=await teamA.post('/api/auth/team').send({key:match.body.teamAKey}),loginB=await teamB.post('/api/auth/team').send({key:match.body.teamBKey}),csrfA=csrfFrom(loginA),csrfB=csrfFrom(loginB);
    const ready=async(team:any,token:string)=>{const snap=(await team.get('/api/team/snapshot')).body,response=await team.post('/api/team/ready').set('x-csrf-token',token).send({expectedVersion:snap.version});expect(response.status).toBe(200)};await ready(teamA,csrfA);await ready(teamB,csrfB);
    const confirm=async(team:any,token:string)=>{const snap=(await team.get('/api/team/snapshot')).body,response=await team.post('/api/team/random-confirm').set('x-csrf-token',token).send({expectedVersion:snap.version});expect(response.status).toBe(200);return response.body};
    let snapshot=(await teamA.get('/api/team/snapshot')).body;expect(snapshot.actions).toHaveLength(1);expect(snapshot.actions[0].randomConfirmation).toEqual({teamAConfirmed:false,teamBConfirmed:false});
    snapshot=await confirm(teamA,csrfA);expect(snapshot.status).toBe('WAITING_FOR_RANDOM_CONFIRMATION');expect(snapshot.actions[0].randomConfirmation.teamAConfirmed).toBe(true);
    await confirm(teamB,csrfB);await confirm(teamA,csrfA);snapshot=await confirm(teamB,csrfB);expect(snapshot.status).toBe('COMPLETED');expect(snapshot.actions).toHaveLength(2);expect(new Set(snapshot.actions.map((action:any)=>action.map.id)).size).toBe(2);
  });
  it('registers Discord accounts and enforces organization member boundaries',async()=>{
    const expiresAt=new Date(Date.now()+86400000).toISOString();
    const orgA=await agent.post('/api/manage/organizations').set('x-csrf-token',csrf).send({name:'Discord 單位 A',expiresAt});
    const orgB=await agent.post('/api/manage/organizations').set('x-csrf-token',csrf).send({name:'Discord 單位 B',expiresAt});
    await prisma.discordAccount.createMany({data:[{discordUserId:'111111111111111111',username:'Operator One'},{discordUserId:'222222222222222222',username:'Operator Two'},{discordUserId:'333333333333333333',username:'Operator Three'}]});
    const assigned=await agent.put('/api/manage/discord-members').set('x-csrf-token',csrf).send({discordUserId:'111111111111111111',organizationId:orgB.body.organization.id});
    expect(assigned.status).toBe(200);
    const orgAgent=request.agent(app),login=await orgAgent.post('/api/auth/organization').send({key:orgA.body.accessKey}),orgCsrf=csrfFrom(login);
    const ownAdd=await orgAgent.put('/api/manage/discord-members').set('x-csrf-token',orgCsrf).send({discordUserId:'222222222222222222'});
    expect(ownAdd.status).toBe(200);
    const pendingId='444444444444444444',pendingAdd=await orgAgent.put('/api/manage/discord-members').set('x-csrf-token',orgCsrf).send({discordUserId:pendingId});
    expect(pendingAdd.status).toBe(200);expect(pendingAdd.body.pendingFirstLogin).toBe(true);expect(await prisma.discordAccount.findUnique({where:{discordUserId:pendingId}})).toBeNull();
    const orgHierarchy=await orgAgent.get('/api/manage/hierarchy'),pendingOperator=orgHierarchy.body.discordAccounts.find((item:any)=>item.discordUserId===pendingId);
    expect(pendingOperator).toMatchObject({username:'尚未登入',pendingFirstLogin:true,loginCount:0});
    const multiOrganization=await orgAgent.put('/api/manage/discord-members').set('x-csrf-token',orgCsrf).send({discordUserId:'111111111111111111'});
    expect(multiOrganization.status).toBe(200);
    expect(await prisma.organizationDiscordMember.count({where:{discordUserId:'111111111111111111'}})).toBe(2);
    expect((await orgAgent.delete('/api/manage/discord-members/222222222222222222').set('x-csrf-token',orgCsrf)).status).toBe(200);
    expect((await orgAgent.delete(`/api/manage/discord-accounts/${pendingId}`).set('x-csrf-token',orgCsrf)).status).toBe(200);expect(await prisma.organizationDiscordMember.count({where:{discordUserId:pendingId}})).toBe(0);
    const context=await agent.get('/api/manage/context');
    expect(context.body.discordAccounts.find((item:any)=>item.discordUserId==='111111111111111111').organizationIds).toEqual(expect.arrayContaining([orgA.body.organization.id,orgB.body.organization.id]));
    expect(context.body.discordAccounts.find((item:any)=>item.discordUserId==='222222222222222222').organizationIds).toEqual([]);
    const edited=await agent.patch('/api/manage/discord-accounts/333333333333333333').set('x-csrf-token',csrf).send({username:'Broadcast Operator',organizationIds:[orgA.body.organization.id,orgB.body.organization.id]});
    expect(edited.status).toBe(200);expect((await prisma.discordAccount.findUnique({where:{discordUserId:'333333333333333333'}}))?.username).toBe('Broadcast Operator');expect(await prisma.organizationDiscordMember.count({where:{discordUserId:'333333333333333333'}})).toBe(2);
    const freshOrgAgent=request.agent(app),freshLogin=await freshOrgAgent.post('/api/auth/organization').send({key:orgA.body.accessKey}),freshCsrf=csrfFrom(freshLogin);expect((await freshOrgAgent.patch('/api/manage/discord-accounts/333333333333333333').set('x-csrf-token',freshCsrf).send({username:'Unauthorized',organizationIds:[]})).status).toBe(403);
    expect((await agent.delete('/api/manage/discord-accounts/333333333333333333').set('x-csrf-token',csrf)).status).toBe(200);expect(await prisma.discordAccount.findUnique({where:{discordUserId:'333333333333333333'}})).toBeNull();expect(await prisma.organizationDiscordMember.count({where:{discordUserId:'333333333333333333'}})).toBe(0);
  });
  it('creates isolated organization, event and BP credentials',async()=>{const expiry=new Date(Date.now()+86400000).toISOString(),org=await agent.post('/api/manage/organizations').set('x-csrf-token',csrf).send({name:'測試單位',expiresAt:expiry});expect(org.status).toBe(201);expect(org.body.accessKey).toMatch(/^.{4}-.{4}-.{4}-.{4}$/);const event=await agent.post('/api/manage/events').set('x-csrf-token',csrf).send({organizationId:org.body.organization.id,name:'測試賽事',description:'',logoUrl:'',startsAt:'',endsAt:'',themeColor:'#ff4655',defaultKeyTtlMinutes:1440,publicSharingEnabled:true,mapIds:Array.from({length:7},(_,i)=>`map-${i+1}`)});expect(event.status).toBe(201);const bp=await agent.post('/api/manage/veto-sessions').set('x-csrf-token',csrf).send({eventId:event.body.id,name:'總決賽',teamAName:'Alpha',teamBName:'Bravo',keyExpiresAt:expiry,overlayTheme:'vct-tc',publicSharingEnabled:true});expect(bp.status).toBe(201);expect(bp.body.teamAKey).toMatch(/^(?=.*[a-z])(?=.*[2-9])[a-z2-9]{8}$/);expect(bp.body.teamBKey).toMatch(/^(?=.*[a-z])(?=.*[2-9])[a-z2-9]{8}$/);expect(bp.body.teamAKey).not.toBe(bp.body.teamBKey);const stored=await prisma.teamAccessKey.findMany({where:{vetoSessionId:bp.body.veto.id}});expect(stored).toHaveLength(2);expect(JSON.stringify(stored)).not.toContain(bp.body.teamAKey);await prisma.vetoSession.update({where:{id:bp.body.veto.id},data:{teamALogo:'/uploads/teams/alpha.png'}});
    const orgAgent=request.agent(app),orgLogin=await orgAgent.post('/api/auth/organization').send({key:org.body.accessKey});expect(orgLogin.status).toBe(200);const orgCsrf=csrfFrom(orgLogin),own=await orgAgent.get('/api/manage/context');expect(own.body.role).toBe('ORGANIZATION');expect(own.body.events).toHaveLength(1);expect(own.body.organizations).toHaveLength(0);expect((await orgAgent.get('/api/manage/server-logs')).status).toBe(403);const serverLogs=await agent.get('/api/manage/server-logs').query({limit:20});expect(serverLogs.status).toBe(200);expect(Array.isArray(serverLogs.body.lines)).toBe(true);
    expect(bp.body.veto.status).toBe('WAITING_FOR_TEAMS');
    const teamA=request.agent(app),teamB=request.agent(app),loginA=await teamA.post('/api/auth/team').send({key:bp.body.teamAKey}),loginB=await teamB.post('/api/auth/team').send({key:bp.body.teamBKey}),csrfA=csrfFrom(loginA),csrfB=csrfFrom(loginB);expect(loginA.body.redirect).toBe(`/bp/teams/${bp.body.veto.id}`);expect(loginA.body.redirect).not.toContain(bp.body.teamAKey);let firstSnapshot=(await teamA.get('/api/team/snapshot')).body;expect(firstSnapshot.viewer.welcomeRequired).toBe(true);expect(firstSnapshot.resultUrl).toBe(`/result/${bp.body.resultToken}`);expect((await teamA.post('/api/team/intro-seen').set('x-csrf-token',csrfA).send({})).status).toBe(204);firstSnapshot=(await teamA.get('/api/team/snapshot')).body;expect(firstSnapshot.viewer.welcomeRequired).toBe(false);const teamPage=await teamA.get(`/bp/teams/${bp.body.veto.id}`);expect(teamPage.status).toBe(200);expect(teamPage.text).toContain('<link rel="icon" href="/uploads/teams/alpha.png">');expect((await request(app).get('/admin')).status).toBe(302);
    const ready=async(team:any,token:string)=>{const snap=(await team.get('/api/team/snapshot')).body,response=await team.post('/api/team/ready').set('x-csrf-token',token).send({expectedVersion:snap.version});expect(response.status).toBe(200)};await ready(teamA,csrfA);await ready(teamB,csrfB);
    const act=async(team:any,token:string,mapId:string)=>{const snap=(await team.get('/api/team/snapshot')).body,response=await team.post('/api/team/action').set('x-csrf-token',token).send({mapId,expectedVersion:snap.version});expect(response.status).toBe(200)};
    const side=async(team:any,token:string,value:string)=>{const snap=(await team.get('/api/team/snapshot')).body,response=await team.post('/api/team/side').set('x-csrf-token',token).send({side:value,expectedVersion:snap.version});expect(response.status).toBe(200)};
    await act(teamA,csrfA,'map-1');await act(teamB,csrfB,'map-2');await act(teamA,csrfA,'map-3');await side(teamB,csrfB,'DEFENSE');await act(teamB,csrfB,'map-4');await side(teamA,csrfA,'ATTACK');await act(teamA,csrfA,'map-5');await act(teamB,csrfB,'map-6');const decider=(await teamA.get('/api/team/snapshot')).body;expect(decider.status).toBe('WAITING_FOR_SIDE_SELECTION');expect(decider.actions.at(-1).action).toBe('DECIDER');expect(decider.actions.at(-1).randomConfirmation).toBeNull();expect(decider.steps[decider.currentStep].sideSelector).toBe('TEAM_A');await side(teamA,csrfA,'ATTACK');const completed=(await teamA.get('/api/team/snapshot')).body;expect(completed.status).toBe('COMPLETED');expect(completed.actions.find((item:any)=>item.stepNumber===6).side).toBeNull();expect(completed.actions.find((item:any)=>item.stepNumber===7).side).toMatchObject({selector:'TEAM_A',selectorSide:'ATTACK'});const firstPlayed=completed.actions.find((item:any)=>item.action==='PICK');const mapResult=await agent.put(`/api/manage/veto-sessions/${bp.body.veto.id}/map-results/${firstPlayed.id}`).set('x-csrf-token',csrf).send({teamAScore:13,teamBScore:9,winner:'TEAM_A',isNextMap:false});expect(mapResult.status).toBe(200);expect(mapResult.body.actions.find((item:any)=>item.id===firstPlayed.id).result).toMatchObject({teamAScore:13,teamBScore:9,winner:'TEAM_A'});const overlayState=await request(app).get(`/api/public/overlay/${bp.body.overlayToken}`);expect(overlayState.body.maps.find((item:any)=>item.mapUuid===firstPlayed.map.id)).toMatchObject({winner:'Team A',score:'13-9'});expect(overlayState.body.maps.find((item:any)=>item.isDecider)).toMatchObject({sideSelector:'Alpha',sideSelection:'ATTACK',atkSide:'Team A'});expect(overlayState.body.seriesScoreA).toBe(1);const publicToggle=await agent.patch(`/api/manage/veto-sessions/${bp.body.veto.id}/public`).set('x-csrf-token',csrf).send({enabled:false});expect(publicToggle.body.publicSharingEnabled).toBe(true);expect((await request(app).get(`/result/${bp.body.resultToken}`)).status).toBe(200);expect((await request(app).get(`/api/public/result/${bp.body.resultToken}`)).status).toBe(200);const englishResult=await request(app).get(`/result/${bp.body.resultToken}?lang=en-US`);expect(englishResult.status).toBe(200);expect(englishResult.headers['content-language']).toBe('en-US');expect(englishResult.text).toContain('Ban/Pick Result');expect(englishResult.text).toContain(`og.png?lang=en-US`);const simplifiedOg=await request(app).get(`/result/${bp.body.resultToken}/og.png?lang=zh-CN`);expect(simplifiedOg.status).toBe(200);expect(simplifiedOg.headers['content-language']).toBe('zh-CN');expect(simplifiedOg.headers['content-type']).toContain('image/png');expect((await request(app).get(`/overlay-vct-tc-i/${bp.body.overlayToken}`)).status).toBe(200);const overlay=await request(app).get(`/overlay-vct-tc/${bp.body.overlayToken}`);expect(overlay.status).toBe(200);expect(overlay.headers['x-robots-tag']).toContain('noindex');
    const other=await agent.post('/api/manage/organizations').set('x-csrf-token',csrf).send({name:'其他單位',expiresAt:expiry});const otherEvent=await agent.post('/api/manage/events').set('x-csrf-token',csrf).send({organizationId:other.body.organization.id,name:'其他賽事',description:'',logoUrl:'',startsAt:'',endsAt:'',themeColor:'#ff4655',defaultKeyTtlMinutes:1440,publicSharingEnabled:false,mapIds:Array.from({length:7},(_,i)=>`map-${i+1}`)});expect((await orgAgent.patch(`/api/manage/events/${otherEvent.body.id}`).set('x-csrf-token',orgCsrf).send({name:'越權修改'})).status).toBe(403);expect((await orgAgent.get('/api/manage/context')).body.events).toHaveLength(1)
  });
  it('recycles and restores an organization hierarchy without changing UIDs',async()=>{const expiry=new Date(Date.now()+86400000).toISOString(),org=await agent.post('/api/manage/organizations-discord').set('x-csrf-token',csrf).send({name:'回收測試單位',description:'',expiresAt:expiry,discordUserIds:[]}),event=await agent.post('/api/manage/events').set('x-csrf-token',csrf).send({organizationId:org.body.organization.id,name:'回收測試賽事',description:'',logoUrl:'',startsAt:'',endsAt:'',themeColor:'#5865f2',defaultKeyTtlMinutes:1440,publicSharingEnabled:false,mapIds:Array.from({length:7},(_,i)=>`map-${i+1}`)}),bp=await agent.post('/api/manage/veto-sessions').set('x-csrf-token',csrf).send({eventId:event.body.id,name:'回收測試 BP',teamAName:'Alpha',teamBName:'Bravo',keyExpiresAt:expiry,publicSharingEnabled:false});const removed=await agent.delete(`/api/manage/organizations/${org.body.organization.id}`).set('x-csrf-token',csrf);expect(removed.status).toBe(200);expect(new Date(removed.body.purgeAt).getTime()-Date.now()).toBeGreaterThan(6.9*86400000);expect(await prisma.organization.count({where:{id:org.body.organization.id,deletedAt:{not:null}}})).toBe(1);expect(await prisma.event.count({where:{id:event.body.id,deletedAt:{not:null}}})).toBe(1);expect(await prisma.vetoSession.count({where:{id:bp.body.veto.id,deletedAt:{not:null}}})).toBe(1);const hierarchy=await agent.get('/api/manage/hierarchy');expect(hierarchy.body.trash.organizations.some((item:any)=>item.id===org.body.organization.id)).toBe(true);const restored=await agent.post(`/api/manage/trash/organizations/${org.body.organization.id}/restore`).set('x-csrf-token',csrf);expect(restored.status).toBe(200);expect(restored.body.id).toBe(org.body.organization.id);expect((await prisma.event.findUnique({where:{id:event.body.id}}))?.deletedAt).toBeNull();expect((await prisma.vetoSession.findUnique({where:{id:bp.body.veto.id}}))?.deletedAt).toBeNull()});
});


describe('event flows and release notes',()=>{
  it('isolates templates, snapshots steps, enforces teams, and completes manual final actions',async()=>{
    const expiresAt=new Date(Date.now()+86400000).toISOString();
    const organization=await agent.post('/api/manage/organizations').set('x-csrf-token',csrf).send({name:'Custom Flow Org',expiresAt});
    const owner=request.agent(app),login=await owner.post('/api/auth/organization').send({key:organization.body.accessKey}),ownerCsrf=csrfFrom(login);
    const outsiderOrg=await agent.post('/api/manage/organizations').set('x-csrf-token',csrf).send({name:'Other Flow Org',expiresAt});
    const outsider=request.agent(app),outsiderLogin=await outsider.post('/api/auth/organization').send({key:outsiderOrg.body.accessKey}),outsiderCsrf=csrfFrom(outsiderLogin);
    for(const lastAction of ['BAN','PICK','DECIDER']){
      const event=await owner.post('/api/manage/events').set('x-csrf-token',ownerCsrf).send({name:`Manual ${lastAction}`,themeColor:'#5865f2',defaultKeyTtlMinutes:1440,publicSharingEnabled:false,mapIds:['map-1','map-2','map-3']});
      expect(event.status).toBe(201);
      const path=`/api/manage/events/${event.body.id}/flows`,steps=[{actor:'TEAM_B',action:'PICK',sideSelector:'TEAM_B'},{actor:'TEAM_A',action:'BAN'},{actor:lastAction==='DECIDER'?'SYSTEM':'TEAM_A',action:lastAction,sideSelector:lastAction!=='BAN'?'TEAM_B':null}];
      expect((await outsider.get(path)).status).toBe(403);
      expect((await outsider.post(path).set('x-csrf-token',outsiderCsrf).send({name:'bad',steps})).status).toBe(403);
      expect((await owner.post(path).send({name:'missing csrf',steps})).status).toBe(403);
      expect((await owner.post(path).set('x-csrf-token',ownerCsrf).send({name:'too long',steps:[...steps,steps[0]]})).status).toBe(400);
      const flow=await owner.post(path).set('x-csrf-token',ownerCsrf).send({name:`Custom ${lastAction}`,steps});expect(flow.status).toBe(201);
      expect((await owner.post(path).set('x-csrf-token',ownerCsrf).send({name:`Custom ${lastAction}`,steps})).status).toBe(409);
      expect((await owner.put(`/api/manage/events/${event.body.id}/maps`).set('x-csrf-token',ownerCsrf).send({mapIds:['map-1','map-2']})).status).toBe(409);
      const body={eventId:event.body.id,name:'Custom match',teamAName:'Alpha',teamBName:'Bravo',keyExpiresAt:expiresAt,flowId:flow.body.id};
      const match=await owner.post('/api/manage/veto-sessions').set('x-csrf-token',ownerCsrf).send(body);expect(match.status).toBe(201);expect(match.body.veto.bestOf).toBe(lastAction!=='BAN'?2:1);
      expect((await outsider.post('/api/manage/veto-sessions').set('x-csrf-token',outsiderCsrf).send(body)).status).toBe(403);
      const modified=steps.map(step=>({...step,actor:step.action==='DECIDER'?'SYSTEM':'TEAM_A'}));
      expect((await owner.put(`${path}/${flow.body.id}`).set('x-csrf-token',ownerCsrf).send({name:'Changed template',steps:modified})).status).toBe(200);
      expect((await prisma.vetoStep.findFirst({where:{vetoSessionId:match.body.veto.id},orderBy:{stepNumber:'asc'}})).actor).toBe('TEAM_B');
      const teamA=request.agent(app),teamB=request.agent(app),loginA=await teamA.post('/api/auth/team').send({key:match.body.teamAKey}),loginB=await teamB.post('/api/auth/team').send({key:match.body.teamBKey}),csrfA=csrfFrom(loginA),csrfB=csrfFrom(loginB);
      const ready=async(team:any,token:string)=>{const snap=(await team.get('/api/team/snapshot')).body,response=await team.post('/api/team/ready').set('x-csrf-token',token).send({expectedVersion:snap.version});expect(response.status).toBe(200)};await ready(teamA,csrfA);await ready(teamB,csrfB);
      let snapshot=(await teamA.get('/api/team/snapshot')).body;
      expect((await teamA.post('/api/team/action').set('x-csrf-token',csrfA).send({mapId:'map-1',expectedVersion:snapshot.version})).status).toBe(403);
      expect((await teamB.post('/api/team/action').set('x-csrf-token',csrfB).send({mapId:'map-1',expectedVersion:snapshot.version})).status).toBe(200);
      snapshot=(await teamB.get('/api/team/snapshot')).body;
      expect((await teamA.post('/api/team/side').set('x-csrf-token',csrfA).send({side:'ATTACK',expectedVersion:snapshot.version})).status).toBe(403);
      expect((await teamB.post('/api/team/side').set('x-csrf-token',csrfB).send({side:'DEFENSE',expectedVersion:snapshot.version})).status).toBe(200);
      for(const mapId of (lastAction==='DECIDER'?['map-2']:['map-2','map-3'])){snapshot=(await teamA.get('/api/team/snapshot')).body;expect((await teamA.post('/api/team/action').set('x-csrf-token',csrfA).send({mapId,expectedVersion:snapshot.version})).status).toBe(200)}
      snapshot=(await teamA.get('/api/team/snapshot')).body;
      if(lastAction==='DECIDER')expect(snapshot.actions.at(-1).randomConfirmation).toBeNull();
      if(lastAction!=='BAN'){
        expect(snapshot.status).toBe('WAITING_FOR_SIDE_SELECTION');
        const pending=await request(app).get(`/api/public/overlay/${match.body.overlayToken}`);expect(pending.body.pendingSideSelector).toBe('Bravo');
        expect((await teamB.post('/api/team/side').set('x-csrf-token',csrfB).send({side:'ATTACK',expectedVersion:snapshot.version})).status).toBe(200);
      }
      snapshot=(await teamA.get('/api/team/snapshot')).body;expect(snapshot.status).toBe('COMPLETED');expect(snapshot.actions).toHaveLength(3);expect(snapshot.actions.some((action:any)=>action.action==='DECIDER')).toBe(lastAction==='DECIDER');
      const overlay=(await request(app).get(`/api/public/overlay/${match.body.overlayToken}`)).body;expect(overlay.maps.map((map:any)=>map.action)).toEqual(['Pick','Veto',lastAction==='BAN'?'Veto':lastAction==='DECIDER'?'Decider':'Pick']);expect(overlay.maps[0]).toMatchObject({actor:'Team B',sideSelector:'Bravo',sideSelection:'DEFENSE'});
      expect((await owner.delete(`${path}/${flow.body.id}`).set('x-csrf-token',ownerCsrf)).status).toBe(200);
      expect(await prisma.vetoStep.count({where:{vetoSessionId:match.body.veto.id}})).toBe(3);
    }
    expect((await owner.post('/api/manage/release-notes').set('x-csrf-token',ownerCsrf).send({version:'unauthorized',body:'text'})).status).toBe(403);
    expect((await agent.post('/api/manage/release-notes').send({version:'no-csrf',body:'text'})).status).toBe(403);
    const note=await agent.post('/api/manage/release-notes').set('x-csrf-token',csrf).send({version:'v-flow-test',body:'New flows\n<script>plain text</script>'});expect(note.status).toBe(201);
    expect((await owner.get('/api/manage/release-notes')).body[0].body).toContain('<script>');
    expect((await owner.patch(`/api/manage/release-notes/${note.body.id}`).set('x-csrf-token',ownerCsrf).send({body:'forbidden'})).status).toBe(403);
    expect((await agent.patch(`/api/manage/release-notes/${note.body.id}`).set('x-csrf-token',csrf).send({body:'Updated details'})).status).toBe(200);
    expect((await owner.delete(`/api/manage/release-notes/${note.body.id}`).set('x-csrf-token',ownerCsrf)).status).toBe(403);
    expect((await agent.delete(`/api/manage/release-notes/${note.body.id}`)).status).toBe(403);
    expect((await agent.delete(`/api/manage/release-notes/${note.body.id}`).set('x-csrf-token',csrf)).status).toBe(200);
    expect((await owner.get('/api/manage/release-notes')).body.some((item:any)=>item.id===note.body.id)).toBe(false);
    expect((await request(app).get('/api/manage/release-notes')).status).toBe(401);
  },30000);
});
